<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Game;
use Doctrine\ORM\EntityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
  public function findAll()
  {
    $results = $this->getEntityManager()
      ->createQuery(
        "SELECT p FROM AppBundle:Game p WHERE p.status='published' ORDER BY p.name DESC"
      )
      ->getResult();

    return $results;
  }



}
