<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Game;
use AppBundle\Request\GameRequest;
use Doctrine\ORM\EntityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{

  public function findAll()
  {
    $results = $this->getEntityManager()
      ->createQuery(
        "SELECT p FROM AppBundle:Game p WHERE p.status='published' ORDER BY p.name DESC"
      )
      ->getResult();

    return $results;
  }

    public function findAllWithTagsByRequest(GameRequest $request)
    {
        $query = $this->createQueryByRequest($request);
        $query->innerJoin('game.tags', 'tags');

        return $query->getQuery()->getResult();
    }

    /**
     * @param GameRequest $request
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function createQueryByRequest(GameRequest $request)
    {
        $qb = $this->createQueryBuilder('game');

        if ($request->getName()) {
            $qb->andWhere('game.name LIKE :name')
                ->setParameter('name', '%' . $request->getName() . '%');
        }

        if ($request->getPublished()) {
            $qb->andWhere('game.status = :published')
                ->setParameter('published', Game::PUBLISHED_STATUS);
        }

        return $qb;
    }

}
